### ISSUE TITLE
Entry <xxx> is a duplicate but no duplicate handling strategy has been set

### ISSUE THREAD

**Issue by alesproch** [TheBoegl/gradle-launch4j#117] opened 2021-10-21 07:48 UTC
It's not possible to set duplicatesStrategy for copying of dependencies into lib folder for createExe/launch4j task.
Using gradle 7.x

**Comment by TheBoegl** [comment] 2021-11-03 21:38
could you please provide a simple working example that you expected to work

**Comment by Shadow-Devil** [comment] 2022-10-18 21:21
Hi, today I faced the same issue.
My minimal build.gradle looks like this:
```groovy
plugins {
    id 'java'
    id 'edu.sc.seis.launch4j' version '2.4.6'
}

dependencies {
    implementation 'org.glassfish.jaxb:jaxb-runtime:3.0.2'
    implementation 'com.sun.xml.bind:jaxb-xjc:3.0.2'
}
```
Both dependencies include a common dependency jaxb-core-3.0.2.jar.

The Error that is being displayed is: 
```
Entry jaxb-core-3.0.2.jar is a duplicate but no duplicate handling strategy has been set. 
Please refer to https://docs.gradle.org/7.1.1/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
```
But when I try to add a duplication handling strategy it doesn't work:
```groovy
plugins {
    id 'java'
    id 'edu.sc.seis.launch4j' version '2.4.6'
}

dependencies {
    implementation 'org.glassfish.jaxb:jaxb-runtime:3.0.2'
    implementation 'com.sun.xml.bind:jaxb-xjc:3.0.2'
}

launch4j {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}
```
This works inside the jar task.

**Comment by Shadow-Devil** [comment] 2022-10-18 21:24
If you could help me with some guidance where the error could be solved, I would like to work on this issue 😄

**Comment by TheBoegl** [comment] 2022-10-19 05:08
This seems to be related to the used copy tasks. You should be able to create a PR adding the strategy there and testing it with the reproducible code snippet you provided.

**Comment by Shadow-Devil** [comment] 2022-10-19 11:43
Is it currently possible to let a test run with a different Gradle version than specified at the root project?

**Comment by Shadow-Devil** [comment] 2022-10-19 12:17
I thought, that maybe something like this would work:
```groovy
launch4j{
    mainClassName = 'com.test.app.Main'
    copyConfigurable = copySpec {
        duplicatesStrategy = DuplicatesStrategy.INCLUDE
    }
}
```
But now I'm getting the error message:
```
Cannot fingerprint input property 'copyConfigurable': value 'org.gradle.api.internal.file.copy.DefaultCopySpec_Decorated@5fd1326f' cannot be serialized.
```
I was looking through the code and found [the copyConfigurable](https://github.com/TheBoegl/gradle-launch4j/blob/d06f305368058c97d5b490fc80855f40b7a6d88e/src/main/groovy/edu/sc/seis/launch4j/CopyLibraries.groovy#L45), that to my understanding should also be settable to a CopySpec.

**Comment by TheBoegl** [comment] 2022-10-19 20:39
There are already some tests in this repo that run against different gradle versions.

I don't have access to my IDE now but you might be able to set the strategy on the `distSpec` variable.

**Comment by Shadow-Devil** [comment] 2022-10-22 23:59
I've created a draft PR (#122) that fixes the issue. It just hardcodes it to exclude any duplicate entries. Maybe we should introduce a new property so the user can specify what DuplicationStrategy should be used.

**Comment by Shadow-Devil** [comment] 2022-11-02 08:12
I think this issue can be closed, since the PR was already merged

**Closed** 2022-11-02 08:42 UTC
Labels: bug, is:fixed
