### ISSUE TITLE
config.xml not generated by ./gradlew -Pl4j-debug createExe

### ISSUE THREAD

**Issue by cbeust** [TheBoegl/gradle-launch4j#100] opened 2020-10-18 13:28 UTC
Launching `./gradlew -Pl4j-debug createExe` does not generate a `config.xml`.

Any other flag I can use to investigate what's going on?

**Comment by cbeust** [comment] 2020-10-18 13:41
Added a few additional checks. In my `build.gradle.kts`:

```
val `l4j-debug`: String by project
println("L4J debug: " + `l4j-debug`.toString())
```

and then:

```
 ./gradlew --stacktrace createExe -Pl4j-debug=true
> Configure project :
L4J debug: true
```

So the property is set but no `config.xml` file gets generated.

**Comment by TheBoegl** [comment] 2020-10-18 14:06
On which plugin and Gradle version are you?

**Comment by cbeust** [comment] 2020-10-18 14:08
Your latest 2.4.8 and Gradle 6.5.1.

**Comment by TheBoegl** [comment] 2021-04-15 22:19
@cbeust could you please verify if either the current version 2.5.0 fixed this issue or that the log output helps?

**Comment by TheBoegl** [comment] 2021-06-16 20:47
Closing this as I'm unable to reproduce.

**Closed by TheBoegl** 2021-06-16 20:47 UTC
Labels: issuer feedback
