### ISSUE TITLE
Plans to update to Launch4j 3.50

### ISSUE THREAD

**Issue by f-cramer** [TheBoegl/gradle-launch4j#144] opened 2023-04-20 21:59 UTC
Launch4j 3.50 was released in late 2022 an includes some major improvements concerning path search. Unfortunately it also renamed multiple properties and changed path search to be the default instead of registry search. Are there any plans to upgrade to 3.50 or would a PR be welcome?

**Comment by TheBoegl** [comment] 2023-04-22 11:52
This is definitely planned but I'm not sure how to adapt the configuration change in 3.50.

**Comment by f-cramer** [comment] 2023-04-26 18:00
Aren't the changes mostly "remove this parameter" and "replace this parameter with this other one"?
I made the changes described [here](https://launch4j.sourceforge.net/docs.html#Configuration_file) in a [fork](https://github.com/f-cramer/gradle-launch4j/commit/1d4d59acda975f60e2508859daf05f204553779c) and (at least for my single use case) it worked just fine.

**Comment by TheBoegl** [comment] 2023-04-26 20:31
That's definitely an easy way to approach this, which will require a new major version as it's a breaking change or we try to deprecate and delegate to replacements with reasonable default values.

**Comment by f-cramer** [comment] 2023-04-26 20:48
I don't think a plugin is really the place to provide backwards compatibility for features that were removed in the main product, is it? But I don't really know how this was handled for previous updates.

**Comment by FritjofH** [comment] 2023-05-09 12:40
I have recently run into the same issues as @f-cramer with issues finding the java path since upgrading to java 17.

I think it would be worth to go for the path of least resistance for this, ie. new major release. Otherwise given the changes below, it wouldn't be that much to delegate and change, right? One thing is removed, and 3 are replaced.

- Removed <bundledJreAsFallback>, path search is always first and registry search second in order to improve compatibility with modern runtimes.
- Replaced <bundledJre64Bit> and <runtimeBits> with <requires64Bit> which works during path and registry search.
- Replaced <jdkPreference> with <requiresJdk> which works during path and registry search.
- Replaced <bundledJreErr> with <jreNotFoundErr>.
- <minVersion> and <maxVersion> are now used during path and registry search, previously they were only checked during registry search.

I'll see if I can find a team member who could assist with this.

**Comment by TheBoegl** [comment] 2023-05-09 16:05
I've spent the last few evenings trying to address this and other issues (#88 and #142) with a new version. Unfortunately some tests are still failing, but I'll stay on it and will hopefully finish the new release during the next few nights.

**Comment by TheBoegl** [comment] 2023-05-21 19:10
@f-cramer, @FritjofH can you please verify that the [latest development](/TheBoegl/gradle-launch4j#using-snapshot-versions) version 3.0.0-SNAPSHOT works for you?

**Comment by FritjofH** [comment] 2023-05-21 19:13
> @f-cramer, @FritjofH can you please verify that the [latest development](/TheBoegl/gradle-launch4j#using-snapshot-versions) version 3.0.0-SNAPSHOT works for you?

Absolutely, will get on it this coming week. Thanks for your work!

**Comment by mattiaslundstrom** [comment] 2023-05-23 12:19
I am working with @FritjofH  and we have now tested the snapshot and it worked well for us.

Only change we had to do is that previously "icon" accepted a file as argument, but now it seems to require a string.
After changing `icon = theFile` to `icon = theFile.getAbsolutePath()` it builds as expected in our environment.

As to whether launch4j 3.50 resolves all the original issues we had with JRE path resolution, this is still being tested.

> > @f-cramer, @FritjofH can you please verify that the [latest development](/TheBoegl/gradle-launch4j#using-snapshot-versions) version 3.0.0-SNAPSHOT works for you?
> 
> Absolutely, will get on it this coming week. Thanks for your work!

**Comment by TheBoegl** [comment] 2023-05-24 07:09
Thanks for your test, @mattiaslundstrom. I'd say that's expected behavior since the icon property as well as other "file-related" properties are defined as `String`.

I've run some more tests on a work-related project and will close this issue as everything seems to work here.

**Closed** 2023-05-24 07:10 UTC
Labels: is:fixed, issuer feedback

**Comment by f-cramer** [comment] 2023-07-04 18:26
I have totally missed this. Just tried the update on one of our projects and it works perfectly. Thanks a lot
